#!/bin/bash

initializeANSI(){
	esc="\033" # if this doesnt work, enter an ESC directly

	# foreground colors
	blackf="${esc}{30m";	redf="${esc}[31m";	greenf="${esc}[32m"
	yellowf="${esc}[33m"	bluef="${esc}[34m";	purplef="${esc}[35m"
	cryanf="${esc}[36m"	whitef=${esc}"[37m"
 
	# background colors
	blackb="${esc}[40m";	redb="${esc}[41m";	greenb="${esc}[42m"
	yellowb="${esc}[43m"	blueb="${esc}[44m";	purpleb="${esc}[45m"
	cyanb="${esc}[46m";	whiteb="${esc}[47m";

	# TO BE CONTINUED. WRITING ALL OF THESE IS EXHAUSTING. 
}
